# Generated by Django 3.2.8 on 2021-10-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlMaletas', '0002_cambios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cambios',
        ),
    ]
